AWSTemplateFormatVersion: '2010-09-09'
Description: Asset storage and delivery

Parameters:
  Hostname:
    Type: String
    Description: The hostname by which assets are retrieved
    MinLength: 1
  ZoneId:
    Type: String
    Description: The id of the zone for the asset domain
    MinLength: 1
    
Resources:
  Origin:
    Type: AWS::S3::Bucket
    Properties: {}
  OriginAccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: Origin
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal: "*"
          Action:
          - s3:GetObject
          Resource:
          - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: Origin
              - "/*"
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - Ref: Hostname
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: S3
          ViewerProtocolPolicy: allow-all
        Origins:
        - DomainName:
            Fn::GetAtt:
            - Origin
            - DomainName
          Id: S3
          S3OriginConfig: {}
  Domain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: ZoneId
      RecordSets:
      - Name:
          Ref: Hostname
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName:
            Fn::GetAtt:
            - Distribution
            - DomainName

Outputs:
  Origin:
    Value:
      Ref: Origin
  Domain:
    Value:
      Ref: Domain
