AWSTemplateFormatVersion: '2010-09-09'
Description: Postgres Database

Parameters:
  BaseDomain:
    Type: String
    Description: The application's domain
    Default: d.cjpowered.com
  Vpc:
    Type: String
    Description: The VPC to which the load balancer attaches.
    MinLength: 1
  DatabaseSubnets:
    Type: String
    Description: The subnets to which the load balancer attaches.
    MinLength: 1
  Env:
    Type: String
    Description: The name of environment
    MinLength: 1
  Performance:
    Type: String
    Description: Performance class
    Default: low
    AllowedValues: [high, low]
  Duration:
    Type: String
    Description: Duration policy
    AllowedValues: [temporary, permanent]
  DBMasterUsername:
    Default: postgres
    NoEcho: true
    Description: The database admin account username
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBMasterUserPassword:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DBSnapshotIdentifier:
    Description: Id of the snapshot to use if you want to restore the db to a previous state
    Type: String
    Default: ""
  DatabaseSecurityGroup:
    Type: String
    Description: Security group provided by network
    MinLength: 1

Conditions:
  Temporary: !Equals [!Ref Duration, temporary]
  Permanent: !Equals [!Ref Duration, permanent]
  BrandNewDB: !Equals [!Ref DBSnapshotIdentifier, ""]

Resources:
  RdsDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets available for the RDS DB Instance
      SubnetIds: !Split
        - ','
        - !Ref DatabaseSubnets

  DBInstanceTemporary:
    Type: AWS::RDS::DBInstance
    Condition: Temporary
    DeletionPolicy: Delete
    Properties:
      Engine: postgres
      EngineVersion: 9.4.7
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      DBName: !If
        - BrandNewDB
        - !Sub ${Env}authservice
        - !Ref AWS::NoValue
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      DBInstanceClass: !FindInMap
      - Performance
      - !Ref Performance
      - InstanceType
      AllocatedStorage: !FindInMap
      - Performance
      - !Ref Performance
      - AllocatedStorage
      DBSubnetGroupName: !Ref RdsDbSubnetGroup
      VPCSecurityGroups: [!Ref DatabaseSecurityGroup]
      AutoMinorVersionUpgrade: true
      AllowMajorVersionUpgrade: true
      PubliclyAccessible: false
      Port: '5432'

  DBInstancePermanent:
    Type: AWS::RDS::DBInstance
    Condition: Permanent
    DeletionPolicy: Snapshot
    Properties:
      Engine: postgres
      EngineVersion: 9.4.7
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      DBName: !If
        - BrandNewDB
        - !Sub ${Env}authservice
        - !Ref AWS::NoValue
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      DBInstanceClass: !FindInMap
      - Performance
      - !Ref Performance
      - InstanceType
      AllocatedStorage: !FindInMap
      - Performance
      - !Ref Performance
      - AllocatedStorage
      DBSubnetGroupName: !Ref RdsDbSubnetGroup
      VPCSecurityGroups: [!Ref DatabaseSecurityGroup]
      AutoMinorVersionUpgrade: true
      AllowMajorVersionUpgrade: true
      CopyTagsToSnapshot: true
      PubliclyAccessible: false
      Port: '5432'
      MultiAZ: true

  DBHostDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: ZZCW5RQ81QPV3
      Name: !Sub ${Env}-db-auth.${BaseDomain}
      Type: CNAME
      TTL: 300
      ResourceRecords:
      - !If
        - Temporary
        - !GetAtt DBInstanceTemporary.Endpoint.Address
        - !GetAtt DBInstancePermanent.Endpoint.Address

Mappings:
  Performance:
    high:
      InstanceType: db.t2.micro
      AllocatedStorage: 5
    low:
      InstanceType: db.t2.micro
      AllocatedStorage: 5

Outputs:
  DBHost:
    Description: The hostname of the provisioned database
    Value: !Ref DBHostDomain
